# Generated by Django 2.1.10 on 2020-03-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_teaches'),
    ]

    operations = [
    ]
