# Generated by Django 2.1.10 on 2020-03-31 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_course_teaches'),
    ]

    operations = [
    ]
